version = 1

test_patterns = ["*_test.go"]

exclude_patterns = [".github/**"]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/auula/bottle"

[[transformers]]
name = "gofmt"
enabled = true