{
    "classdb": {
        "port": 2468,
        "dbpath": "/var/classdb/data",
        "file_size_bytes": 1024,
        "io_mode": "mmap",
        "authentication": "password@123",
        "logging": "/var/log/classdb.log",
        "url_prefix": "/rpc",
        "encoder": {
            "enable": true,
            "secret": "/etc/classdb/encrypt.wasm"
        },
        "compresser": {
            "enable": true,
            "mode": "hot",
            "hotspot": 1000,
            "second": 15000
        }
    }
}