classdb:
    port: 2468                              # 服务 HTTP 协议端口
    dbpath: /var/classdb/data               # 数据库文件存储目录
    file_size_bytes: 1024                   # 默认个数据文件大小，单位 KB
    io_mode: mmap                           # 默认为 Direct/IO，另外可以设置 mmap 模式
    authentication: password@123            # 访问 HTTP 协议的秘密
    encoder:
        enable: TRUE                        # 是否开启加密器
        secret: /etc/classdb/encrypt.wasm   # 自定义加密逻辑实现
    compresser:
        enable: TRUE        # 是否开启数据压缩功能
        mode: hot           # 垃圾回收策略 默认为周期性 
        # 下面两项是可选择项，hot 模式对应 hotspot 值，cycle 模式对应  second 值
        hotspot: 1000       # 默认一个键被操作 1000 次就为热点
        second: 15000       # 默认为周期性，单位秒


